small fixes and bump minimum GCC version to 4.9.1
tgeijten/flut pull request #11
Opened 2016-11-29 19:36 UTC by carmichaelong

@tgeijten Let me know if you want any changes before you merge.

2016-12-05 14:09 UTC, tgeijten requested changes

2016-12-05 14:09 UTC, tgeijten commented on flut/system_tools.cpp
> +#else
Doesn't the result get stored in `arr`? If so, you can directly create a string from that and omit the `stringstream`.

2016-12-05 18:35 UTC, carmichaelong commented
You're definitely right. Should be fixed now.

2016-12-07 20:11 UTC, tgeijten commented on flut/system_tools.cpp
>  		return str;
Now that we're nitpicking... ;-) Just write `return string( arr )`. It's shorter and immediately clear that the returned value is an rvalue.

2016-12-07 20:11 UTC, tgeijten approved these changes

2016-12-07 20:12 UTC, merged

2016-12-07 21:10 UTC, carmichaelong commented on flut/system_tools.cpp
>  		return str;
I appreciate the nitpicking! I still have much C++ to learn... Thanks for the merge!